### ISSUE TITLE
Options to have new lines in <script> and keeping indentation.

### ISSUE THREAD

**Issue by AlicanC** [popeindustries/inline-source#10]
Currently when a script is inlined without compress, this is the result:

```html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">

        <script>!function(e, t, n, s) {
  "use strict";
  var a = t.createElement(n), c = t.getElementsByTagName(n), r = c[0];
  a.async = !0, a.src = s, r.parentNode.insertBefore(a, r);
  var m = function() {
    m.stack.push(arguments);
  };
  m.stack = [], e.asd = m;
}(window, document, "script", "../script.js");</script>
    </head>
    <body>
        <stuff></stuff>
    </body>
</html>
```

It would be nice to have new lines after <script> and before </script> and also keeping the indentation:

```html
<!doctype html>
<html>
    <head>
        <meta charset="utf-8">

        <script>
            !function(e, t, n, s) {
                "use strict";
                var a = t.createElement(n), c = t.getElementsByTagName(n), r = c[0];
                a.async = !0, a.src = s, r.parentNode.insertBefore(a, r);
                var m = function() {
                    m.stack.push(arguments);
                };
                m.stack = [], e.asd = m;
            }(window, document, "script", "../script.js");
        </script>
    </head>
    <body>
        <stuff></stuff>
    </body>
</html>
```

**Comment by popeindustries** [comment]
Thanks for the idea. Because in many cases it is necessary to inline already compressed source (with `compress: false`), I think the best way to accomplish this would be another flag. Something along the lines of `pretty: true`. Would that work?

**Comment by popeindustries** [comment]
Looks like I am able to come close:

```html
<!DOCTYPE html>
<html>
<head>
    <title></title>
    <script>
    var foo = 'foo'
      , bar = 'bar';

    function baz () {
      console.log('baz');
    }
    </script>
</head>
<body>

</body>
</html>
```
Unfortunately, indenting the source content one more column would necessitate extra parsing to determine the tab type (space or tab) and size, so the easiest would be to leave the content aligned with the enclosing `<source>` tags.

**Comment by popeindustries** [comment]
Feel free to check out the `pretty` branch and take a look.

**Comment by AlicanC** [comment]
I got extra new lines in my output because the RegExp in `getPadding()` matched `\n(8 spaces)` instead of `(8 spaces)`.

Replacing `'^(\\s+)'` with `'^([\\t ]+)'` solved the issue, but I don't really get why "\s" matches the new line there. Shouldn't the "m" flag consume them?

**Comment by popeindustries** [comment]
I'm not sure how the `m` flag changes things, but `\s` does match spaces, tabs, and new lines. 

Thanks for the fix, and I'll be sure to push this out right away.

**Comment by AlicanC** [comment]
I assumed that the `m` flag worked like `.split('\n')` which would make new line characters go away, but it looks like it does not. I'm not sure if this should be the behavior but I'm not the one to challenge the RegExp spec.

Thanks for the implementation :thumbsup:
