### ISSUE TITLE
Inline only CSS or JS

### ISSUE THREAD

**Issue by hanifbbz** [popeindustries/inline-source#11]
We're building a Web Component which has some styling and CSS. We use `gulp-inline` wrapper: https://www.npmjs.com/package/gulp-inline
This tool is great because it allows us to embed the CSS and JS into one distributable HTML file.
However, during the development phase, we want our HTML to only contain the inline-css and keep javascript in separate file (as-is) in order to simplify our debug cycle.

However, currently it is not possible to only pick CSS or JS for inlining. Would it be possible to add two options that are true by default:

```
inlineCSS: true,
inlineJavascript: true
```

**Comment by popeindustries** [comment]
That seems reasonable. I'll take a look.

**Comment by popeindustries** [comment]
Added to `master` now with `options.inlineJS && options.inlineCSS`. I'm just waiting for feedback on #10 before releasing, but feel free to give it a try and let me know.

**Comment by hanifbbz** [comment]
This doesn't seem to work in 3.X. what is the alternative way? Would you include some examples in the README?

**Comment by popeindustries** [comment]
The api has changed in 3.x to allow ignoring by tag or type. Take a look at the following test to see the new syntax: https://github.com/popeindustries/inline-source/blob/master/test/5-inline-test.js#L167

I'll make a note to improve the docs.

**Comment by popeindustries** [comment]
I've decided to simplify the options config so that it accepts a string (or array) of tags/types instead of using an object:

```js
inline('something.html', { ignore: ['js', 'img'] }, function (err, html) { //... });
```

Will be released in v4.x

**Comment by hanifbbz** [comment]
Love it.

I kinda like it when the option for raster images (png, jpg, gift, etc.) is separate from vector (svg). Would it be possible to `ignore` only png images but inline svg?

**Comment by popeindustries** [comment]
Good idea. I've now added `format` as well, so 'gif/png/jpeg/svg' are also valid, even though they have the same tag (img) and same type (image).
