### ISSUE TITLE
When not inlining a type of resource, can you leave the attribute untouched?

### ISSUE THREAD

**Issue by hanifbbz** [popeindustries/inline-source#12]
This is related to our earlier issue #11. Excellent job on fixing it, but there is a caveat that has been complicating out build system to work around. I wish it could be solved at the source.

In our team we inline the CSS by setting the `inlineJS` option to `false`. Works awesome. Let's call this file `X`.
But then when we're finished with debugging, we want to take `X` and run it through your code again to minify Javascript, this time with `inlineJS` flag set to true.

Unfortunately this doesn't work. Because the first time that we ran the file through your code, it removes the `inline` attributes (even the ones on the Javascript tags).

So to solve this issue, we need the following functionality:
1. When `inlineJS` flag is false, don't touch `inline` attribute on scripts
2. When `inlineCSS` flag is false, don't touch `inline` attribute on link[rel=stylesheet]
3. Otherwise, remove the `inline` attribute for every resource **that is inlined**

Thank you

**Comment by popeindustries** [comment]
aha! Of course. Sorry. Fix coming right up

**Comment by hanifbbz** [comment]
Great mate. I'll try to persuade my company to pay you a tip. Do you have a gittip account?

**Comment by popeindustries** [comment]
Ha, thanks for the offer, but that's not necessary. Glad you guys can use it!
