### ISSUE TITLE
Incorrect handling of link tags

### ISSUE THREAD

**Issue by clarfon** [popeindustries/inline-source#122]
It thinks this is a stylesheet and inlines it as `<style>`, which is wrong:

```
<link rel="manifest" href="index.webmanifest">
```

This should inline as a base64 URI instead.

**Comment by spock123** [comment]
Just ran into same issue - a Googl search let me here

**Comment by spock123** [comment]
@clarfon you can manually skip replacement.. I added the following handler which just sets content to be the matching string:

```
handlers: [
    (source, context) => {

      if(source.sourcepath === 'manifest.json') {
        source.content = source.match;
      }

      return Promise.resolve();
    }
  ]
```

**Comment by popeindustries** [comment]
Version `7.0.0` is now more strict with respect to handling of `rel`, where only `stylesheet` or `icon` are parsed (missing `rel` is assumed to be `stylesheet`)
