### ISSUE TITLE
Ignore or inline source maps

### ISSUE THREAD

**Issue by clarfon** [popeindustries/inline-source#123]
Right now, the inlined files still retain the source map declaration, which can be confusing. There should be an option to either remove it or directly inline the source maps into the file.

**Comment by popeindustries** [comment]
I think having to modify source file content lies a little outside the scope of this library. 

If source map declarations are causing errors, you could write your own [custom handler](https://github.com/popeindustries/inline-source/blob/master/README.md#custom-handlers) to strip the source map before the content is inlined (by modifying `source.fileContent`).

**Comment by clarfon** [comment]
That's fair. I felt that source maps could technically be included because they are, in a sense, a separate resource to be inlined, and the parsing is simple. But I will rely on custom handlers instead, if that's preferred!
