### ISSUE TITLE
RegExp won't match tags in minified files

### ISSUE THREAD

**Issue by AlicanC** [popeindustries/inline-source#13]
I have a build process in which HTML files first get minified (with html-minifier) and then get their scripts inlined. The problem is that the RegExp used to match tags won't detect anything in a single line HTML file.

I must say that it's absolutely possible to minify the file after inlining which would make this problem disappear since I have no reason to minify the file before inlining. I just want to point this out.

A simple modification could make the RegExp match a minified file, but then it would also match tags in comments and probably in other places where we don't want it to.

Again, I can fix my problem by swapping two lines in my build process, but using something like jsdom or htmlparser to find tags might be considered in the future for the sake of completeness.

In the meantime, the documentation can be updated to elaborate how inline-source actually looks for tags.

**Comment by popeindustries** [comment]
Thanks for the heads up. Can you paste an example I can test with? I think I'd like to avoid parsing/tokenising if I can for the time being.

**Comment by AlicanC** [comment]
I had to remove names since I'm working on a propriety project, but it should be enough to debug the code that matches tags:
```html
<!doctype html> <html lang="en"> <head> <meta charset="utf-8"> <base href="/"> <title>***</title> <meta name="description" content="***"> <meta name="author" content=""> <meta name="viewport" content="width=device-width,initial-scale=1"> <link rel="shortcut icon" href="***"> <link rel="shortcut icon" type="image/x-icon" href="***"> <script type="application/json" src="data/***.json" data-name="***" inline></script> <script type="application/json" src="data/***.json" data-name="***" inline></script> <script type="application/json" src="data/***.json" data-name="***" inline></script> <script src="***" inline></script> <script src="scripts/***.js" inline></script> <script src="scripts/***.js" inline></script> <script src="scripts/***.js" inline></script> </head> <body> </body> </html>
```

These are the [html-minifier](https://github.com/kangax/html-minifier) options I used (some may be defaults):
```javascript
{
removeComments: true,
collapseWhitespace: true,
conservativeCollapse: true,
collapseBooleanAttributes: true,
caseSensitive: true
}
```

---

I have also noticed that all attributes are lost after inlining. (This has nothing to do with minification, but using a parser would also solve this.)

For example this:
```html
<script type="application/json" src="myData.json" data-name="myData" inline></script>
```
becomes:
```html
<script>
{"foo":"bar"}
</script>
```

Parsing the HTML would make it easier to keep these attributes. (Parse it, find tags, remove "src" and "inline" attributes, change innerText, done and we didn't touch anything that is not our business.)

I would love to fix these in a PR, but my job keeps me really busy these days. If you agree that HTML parsing should be something that inline-source does, I will check with you when I have the time and do it if you haven't done it already.

**Comment by popeindustries** [comment]
It sounds like it would be a great enhancement, so I'm up for giving it a try. I'll close this for now and we can track progress in #14. Thanks.
