### ISSUE TITLE
Replace RegExp parsing with proper html parser

### ISSUE THREAD

**Issue by popeindustries** [popeindustries/inline-source#14]
Need to find an esprima equivalent for parsing HTML. Some candidates:
- https://github.com/tautologistics/node-htmlparser
- https://github.com/tmpvar/jsdom (not sure if it's possible to access tokens and serialize)
- https://github.com/cheeriojs/cheerio

ref #13

**Comment by AlicanC** [comment]
I investigated jsdom a little bit. Since it wants to act like a browser, when you pass it a fragment like `<script>blah</script>`, it turns it into `<html><body><script>blah</script></body></html>`. We might expect users to pass a complete HTML file instead of a fragment, but we shouldn't mess with the structure anyway. ("Minding our own business.")

jsdom uses parser5 internally and it doesn't do that so I am investigating parser5 at the moment.

**Comment by AlicanC** [comment]
This mess of a code gets the job done:
```javascript
var path = require('path');
var fs = require('fs');
var parse5 = require('parse5');
var parse5Utils = require('parse5-utils');
var _ = require('lodash');

var parser = new parse5.Parser();
var serializer = new parse5.Serializer();

var fragment = parser.parseFragment('<head><script type="application/json" src="fixtures/foo.json" data-name="foo" inline>asd</script><script></script></head>');

var tags = ['script'];
var inlineAttribute = 'inline'


var checkNode = function (node) {

	if (tags.indexOf(node.tagName) === -1)
		return false;

	//Check if the inline attribute exists
	if (!_.find(node.attrs, {name: inlineAttribute}))
		return false;

	//Remove the attribute
	node.attrs = _.reject(node.attrs, {name: inlineAttribute});

	var src = _.find(node.attrs, {name: 'src'}).value;

	//Remove the attribute
	node.attrs = _.reject(node.attrs, {name: 'src'});

	//Read the file
	var content = fs.readFileSync('test/' + src);

	//Create a text node
	var textNode = parse5Utils.createTextNode(content);

	//Append the text node
	parse5Utils.append(node, textNode);

	/*console.log(src);

	console.log(node);*/

	return true;

};

var searcher = function (node) {

	if (!checkNode(node) && node.childNodes) {
		node.childNodes.forEach(searcher);
	}

};

searcher(fragment);

console.log(serializer.serialize(fragment));
```

Since parser5 doesn't have methods like `getElementsByTagName()`, we have to recurse manually to find nodes. lodash helps us to find and remove attributes. parse5-utils helps us to create a text node in tags we inline.

**Comment by popeindustries** [comment]
Great stuff

**Comment by popeindustries** [comment]
I just realised there may be a use case that would probably stop working if we switched away from naive RegExp parsing: I also use inline-source on templates (nunjucks, for example), before precompiling them to JavaScript. Maybe we would have to have a fallback to RegExp if parsing fails, or if the file extension isn't `.html`.

**Comment by hanifbbz** [comment]
+1 we had a problem with the RegExp. The scenario is like this:

We append the `<script>` tags at the end of the html file and save it. So we end up with something like this:

````
...
<template><script src="all.js></script>
````

Later we use `inline-source` to inline those source files but it fails. However if the script tag starts on a new line this problem doesn't happen.

**Comment by hanifbbz** [comment]
Maybe you can use the rather popular project Cheerio?
https://github.com/cheeriojs/cheerio

**Comment by AlicanC** [comment]
I think the most important thing is to decide what will the API become after this. I can add more problems here:

1- We want to handle complexity, but it's hard because we use RegExp. (This issue.)
2- We do I/O, but we are synchronous.
3- We want to handle more elements (like `<img>`), but the code isn't really modular.

I have just brought up 2 and 3, so @popeindustries is yet to agree or disagree. Even without 2 and 3, we need to rewrite a lot. 2 and 3 will be a lot easier to implement if we decide to do it know rather than later.

If we are going to answer this call for version 2 with a breaking API, I'd love to see these features in it:

**Completely asynchronous API**

We can use kriskowal/q in our code to do this. Stuff we expose to users can have two modes:
```javascript
var callback = function (err, result) {
    
};

inline(options, callback);

// OR

inline(options)
    .then(function (result) {

    })
    .catch(function (err) {

    });
``` 

**Different handlers depending on formats instead of tags**
```html
<!-- We don't care, because there is no "inline" attribute. -->
<script src="path/to/file.js"></script>

<!-- Handler is automatically set to JavaScript because that's how browsers do it. -->
<script src="path/to/file.js" inline></script>

<!-- Handler is unknown, because there is a "type" attribute and we don't know how to handle it.
    We pass it (or error depending on the configuration). -->
<script type="application/blah" src="path/to/file.js" inline></script>

<!-- Handler is unknown, we pass it (or error depending on the configuration). -->
<img src="path/to/image" inline></img>

<!-- Handler "PNG" is detected from extension. -->
<img src="path/to/image.png" inline></img>

<!-- Handler "JPG" is explicitly set. -->
<img src="path/to/image" inline="JPG"></img>
```

**Passing per-tag configuration to handlers**
```html
<!-- "inline-minifier" attribute overrides the default configuration for the "JavaScript" handler. -->
<script src="path/to/file.js" inline inline-minifier="uglifyjs"></script>

<!-- "inline-variable" attribute is required by the "JSON" handler. -->
<script type="application/json" src="path/to/file.json" inline inline-variable="window.MyAppConfig"></script>
<!-- This becomes: -->
<script>window.MyAppConfig = {"foo": "bar", "baz": "boo"};</script>
```

**Configuring handlers and turning them on or off**
```javascript
inline({
    file: 'path/to/file.html',
    handlers: {
        // false: Do not use the handler.
        // true: Use the default handler.
        // Object: Set options for the handler.
        'LESS': false,
        'CSS': true,
        'PNG': false,
        'SVG': true,
        'JavaScript': {
            minify: false
        },
        'JSON': {
            // Set custom handler
            handler: myJsonHandler,

            // Set options for it
            minify: false
        }
    }
});
```

**Custom handler support (which will be exposing our inside handler API to users)**
```javascript

var myJsonHandler = new inline.Handler(['script'], function (args, config, tag) {
    
    // "args" is the argument list generated by inline-source
    //     which is derived from global configuration, handler configuration
    //     and attributes of the tag.
    // "config" is the global configuration object.
    // "tag" is the parsed tag. Format depends on the parser we use.

    // Check if this is the type we need.
    // We don't use "tag.attributes['type']" because inline-source can do its own type detection.
    if (args.type !== 'application/json') {
        // This handler doesn't care.
        return true;
    }

    // Check if we have the required configuration
    // Like before, we don't use "tag.attributes['inline-variable']"
    // because maybe the user changed the "attribute" configuration to "myattr"
    // so the "variable" setting is in "myattr-variable" instead of "inline-variable".
    if (!args.variable) {
        // This handler needed this tag so much!
        return new Error('Required attribute "inline-variable" not found!');
    }

    return Q.nfcall(FS.readFile, args.src, 'utf-8')
        .then(function (contents) {

            // inline-source could remove this automatically
            // This is actually a lot more complicated with Parse5
            delete tag.attributes.src;

            // This could be something less painful and less dependant to the parser
            tag.childNodes = [{
                type: 'text',
                contents: args.variable + '=' + JSON.parse(args.src);
            }];

            return tag;

        });

});
```

**Parsing method (RegExp/Parse5) independent API for handlers**
```javascript
// Inside inline-source

// Look for tags with RegExp
// I don't think we have to look for tags with parse5
// We just have to parse them with a proper parser to modify it correctly
// Doing it this way will enable us to work on non-HTML files
var tags = findTagsWithRegExp();

tags.forEach(function (tag) {

    // Parse the tag
    var parsedTag = parseWithParse5(tag);

    // Build the args and config
    var handlerArgs = blah;
    var handlerConfig = blah;

    // Get handlers
    var handlers = getHandlersWhichWantToHandleTag(tag.type);

    handlers.forEach(function (handler) {

        var ret = handler.handle(handlerArgs, handlerConfig, parsedTag);

        if (ret === true) {
            // This handler didn't do anything, we can pass the tag to another handler.
            isHandled = false;
        } else if (isError(ret)) {
            // The handler errored. Stop working and throw.
        } else if (isPromise(ret)) {
            // The handler promised us to resolve with an inlined tag. Move to the next tag.
            isHandled = true;
        }

    });

    if (!isHandled) {
        // We went through all handlers and none of them handled this tag.
        // If the configuration tells us to ignore unhandled tags, continue.
        // Stop working and throw otherwise.
    }

});
```

I have made some progress on these in my branch, but it's incomplete and I was following some other ideas back then. If we can decide on the API, I can do all the required coding.

**Comment by popeindustries** [comment]
Thank you for putting so much careful thought into this @AlicanC! It's a rather dense post, but I'll see if I can address some of the more general points.

**async**
I have nothing against adding an async interface, however I'd prefer sticking with a "nodeback" interface over Promises. I don't have anything against Promises in general, but just feel that callbacks are more flexible (can be wrapped as Promises, thunks, etc), especially since `inline-source` may be used in different types of build pipelines. I kind of like the following (though I admit it may be a little old school):

```js
// Async by default
inline(src, options, function (err, html) {
  // Do something with html or err
});

// Sync variation
var html = inline.sync(src, options);
```

**modularity**
Breaking things up into modular handlers for each source type is a great idea. I would, however, like to avoid the complexity of a plugin-type interface. I wonder if we can approach it more like a middleware stack, where both internal and external handlers can choose to modify or ignore as necessary? This obviously needs more thought, but if we are able to identify the `type` as you suggest (file extension, type attribute, etc), all handlers could have the same basic interface:

```js
function handler (source, next) {
  if (source.type != 'js') return next();
  // Modify 'source' in some way by loading content, compressing, etc
  //...
};
```

After parsing each inline element, the first handler in the stack would be a content loader, followed by one or more external "user" type handlers, our internal default type handlers, and finally default compression handler. We would need to find a nice way to notify downstream handlers that the content has already been "handled", but I think it would be simple enough while at the same time allowing full external control over the final written output.

**parsing**
I'm interested in the 2-step approach you suggest (regex first, then parser). We would need to experiment here, but I think we are all in agreement that parsing needs to be improved.

Thanks again for the input and inspiration. Spring has arrived here in Norway, but as soon as the sun sets, I'll get started on v2.

**Comment by AlicanC** [comment]
As long as we are going to support async with node style callbacks, it doesn't really matter if we return a promise or not. Why do you want to keep a sync version though? Just like users can turn `inline()` to a promise with https://github.com/kriskowal/q, they can make it sync with https://github.com/abbr/deasync.

**Comment by popeindustries** [comment]
Speed, basically. Over the last 4-5 years, I've written and rewritten my build system to use sync or async io, and callbacks, promises, or generators for control flow. Sync io and callbacks are by far the fastest for this particular use case, even when processing several hundred files at the same time.

**Comment by popeindustries** [comment]
Sorry for the wait, but I think I'm (finally) happy with the v2.0 branch. There are no docs yet, but please take a look and let me know what you think.

In general, parsing is done in two steps: a (better) regex match for any tags with `inline` attribute, then [htmlparser2](https://github.com/fb55/htmlparser2) (same as cheerio.js) to parse attributes. Take a look at [match.html](https://github.com/popeindustries/inline-source/blob/v2.0/test/fixtures/match.html) to see if I'm missing any matching scenarios. Once matched, sources are run through a middleware pipeline (load, [custom handlers], js, css, wrap, inline). By specifying handlers in `options.handlers`, you will have full control over handling custom or default types/tags (see [tests](https://github.com/popeindustries/inline-source/blob/v2.0/test/5-inline-test.js#L268-L277) for example). [*Because of the custom handling abilities, I've decided to drop the sync api.*]

As far as I'm concerned, the only remaining items are docs, backwards compatibility warnings/handling, and possibly hooks for integrating with my build system (need 2-step parse + inline). We are almost there!

/cc @AlicanC @hanifbbz

**Comment by AlicanC** [comment]
I can't believe I couldn't check what's going on for 17 days. Sorry for being super busy with other stuff.

I am currently working on another project which doesn't use inline-source, but I hope I will be back to the other one soon. I might make more intense use of inline-source in the future, which will involve inlining a lot of `<script type="application/json">`s. (Holy moly, you even have a JSON inliner in your tests!) I hope we prevented most of the performance hit with the "RegExp + Parse" idea. (You know, instead of parsing the whole HTML.)

Anyways, great job :+1:

**Comment by popeindustries** [comment]
Glad you approve ;)

Get in touch again later on and we can see if we can formalise that JSON handling (and any other issues that pop up). Take care.
