### ISSUE TITLE
Inlining scripts that have tags in strings are problematic.

### ISSUE THREAD

**Issue by circlingthesun** [popeindustries/inline-source#16]
Consider:

```html
<script>
var test = 'foo... </script> bar.....';
</script>
```

The script tag inside the string will be detected as the end of the block. Tags should be escaped when inlining JS.

See: http://stackoverflow.com/questions/1659749/script-tag-in-javascript-string

**Comment by popeindustries** [comment]
Thanks for the link @circlingthesun. This has been discussed before (#9), but I'll take another look at escaping the tag: `document.write('<script src="foo.js">\x3C/script>')`

I'm about to release a substantially updated 2.0 version soon, but I'll make sure to add this if it works.

**Comment by popeindustries** [comment]
Hopefully fixed in newest v2.0
