### ISSUE TITLE
Multiple root directories

### ISSUE THREAD

**Issue by alexsomeoddpilot** [popeindustries/inline-source#17]
Are there any plans to support multiple root directories?

I currently serve content from multiple directories during my local dev process and want to inline content from both for distribution.

**Comment by popeindustries** [comment]
That's an interesting idea. Can you give me an example of how you like to set things up? If you set a root path far enough up the tree you should be able to reach any directory you'd like.

**Comment by alexsomeoddpilot** [comment]
The problem is that the content isn't being served from the shared root.

The directory looks something like this:
```
+-- project root
    |
    |   compiled files
    +-- build
    |   |
    |   +-- index.css
    |
    +-- src
        |
        +-- index.js
```

While the HTML content looks something like this:
```html
<link href="index.css">
<script src="index.js"></script>
```

**Comment by popeindustries** [comment]
What prevents you from using relative paths from the project root (default root dir)?

```html
<link href="build/index.css" inline>
<script src="src/index.js" inline></script>
```
