### ISSUE TITLE
illegal operation on a directory, read

### ISSUE THREAD

**Issue by MartijnHarmenzon** [popeindustries/inline-source#194]
When trying to use:
```
    .src([
      './dist/**/index.html'
    ])
    .pipe(inlinesource())
    .pipe(gulp.dest('./dist/'));
```

It fails.

```
    .src([
      './dist/analytics/index.html'
    ])
    .pipe(inlinesource())
    .pipe(gulp.dest('./dist/'));
```

Fails also.

The following works:
```
    .src([
      './dist/index.html'
    ])
    .pipe(inlinesource())
    .pipe(gulp.dest('./dist/'));
```

But I need to inline the code in the analytics folder also. 

Error message:

Message:
    EISDIR: illegal operation on a directory, read
Details:
    errno: -4068
    syscall: read
    code: EISDIR
    domainEmitter: [object Object]
    domainThrown: false

**Comment by popeindustries** [comment]
It looks like you're using the gulp plugin. I don't know how that works, especially when using file grepping. This library only accepts one file source at a time.
