### ISSUE TITLE
Place to post recipes

### ISSUE THREAD

**Issue by Misiur** [popeindustries/inline-source#21]
Hello! I'd like to share a [recipe of mine](https://gist.github.com/Misiur/94af7a97247bd61dde6a), however I'm not sure where. Do you intend to create a wiki for such snippets?

**Comment by popeindustries** [comment]
Hi! I'm open to suggestions. It's also possible to publish handlers to npm, but in this case, you could open a pull request to add the `type` to our lookup.

**Comment by Misiur** [comment]
The problem is that injector removes type attribute completely. [HTML5 doesn't require type attribute](http://www.w3.org/html/wg/drafts/html/master/semantics.html#the-script-element), and I guess most people inline scripts to save space, so unnecessary type attribute would be annoying. My solution started as a hack, but it takes less space than creating a valid new "type" of script - but it doesn't fit the current flow. So I guess I'll just leave it here as it is for people to find it via google for inlining shaders.
