### ISSUE TITLE
Keep svg image id and classes

### ISSUE THREAD

**Issue by frzsombor** [popeindustries/inline-source#22]
If I inline a basic (jpg/gif/etc) image, the final image tag will still have the ID and CLASS that it had before. However, if I inline an SVG, the `<img>` tag will be removed, and replaced by the `<svg>` so I loose the id and classes. I've looked at the code and I'm sure it won't be hard for you to do, but unfortunately it would be hard for me. I really hope you can help me by adding this feature, because I work with pure hand-written html5 banners, and your project helps me so much.

**Comment by popeindustries** [comment]
I'll definitely take a look at this. It will be a little work to parse the incoming svg document to read/replace attributes, but it should be possible.

**Comment by popeindustries** [comment]
Fixed in 4.1.1
