### ISSUE TITLE
Attributes are removed from SVG files

### ISSUE THREAD

**Issue by wdamien** [popeindustries/inline-source#24]
When using version 4.1.1 all the attributes are stripped from SVG files and replaced with these default values: ```x="0" y="0" viewBox="0 0 100 100"```.

To reproduce use this sample svg:
```
<svg xmlns="http://www.w3.org/2000/svg" x="0px" y="0px" width="1024px" height="768px" viewBox="0 0 1024 768" enable-background="new 0 0 1024 768" xml:space="preserve">
    <rect x="27.5" y="115.5" fill="#FFFFFF" stroke="#000000" stroke-miterlimit="10" width="94" height="94"/>
</svg>
```

After its been inlined all the attributes are removed, and this is the resulting SVG:
```
<svg x="0" y="0" viewBox="0 0 100 100"><rect x="27.5" y="115.5" fill="#FFFFFF" stroke="#000000" stroke-miterlimit="10" width="94" height="94"></rect></svg>
```
Which makes the svg display completely different then expected.  For now my workaround is to fallback to 4.0.0.

**Comment by popeindustries** [comment]
Should be fixed now in 4.2.0
