### ISSUE TITLE
Images from CSS files not inlined

### ISSUE THREAD

**Issue by KyleMaas** [popeindustries/inline-source#244]
Images (such as those used as backgrounds) in a CSS file do not seem to be inlined properly.

**Comment by popeindustries** [comment]
No sources are currently parsed for inlineable sub-resources. Although this is a good idea, parsing css or js would add a whole level of extra complexity, and go far beyond the modest goals of this project (turning it into a general purpose build tool). Although it's more work for users, setting up a PostCSS or similar build task to pre-process css before inlining is not prohibitively difficult. Sorry to disappoint, but I won't be considering such a major upgrade anytime soon.

**Comment by KyleMaas** [comment]
Okay.  Thank you for the response.
