### ISSUE TITLE
using absolute paths breaks

### ISSUE THREAD

**Issue by kilianc** [popeindustries/inline-source#27]
if `dist/index.html` contains

```html
<img src="/dist/images/foo.png">
```

the path is resolved to `/dist/dist/images/foo.png`

**Comment by popeindustries** [comment]
And the current working directory is `dist`'s parent? With no `rootpath` set?

**Comment by kilianc** [comment]
yes that should default to `pwd` which is where I run gulp from

**Comment by popeindustries** [comment]
The desired behavior is the same as in a browser, where webroot is equivalent to `process.cwd()` (or `rootpath` if it is set), and all absolute paths resolve from that point. The only way I'm able to reproduce the above behavior is if `dist` is the current working directory or set as `rootpath`. Would you be able to add a `console.log(rootpath);` in [lib/utils.js#74](https://github.com/popeindustries/inline-source/blob/master/lib/utils.js#L74) and see what `rootpath` is resolving too?

**Comment by popeindustries** [comment]
These tests currently pass:

```js
expect(utils.getSourcepath('/dist/images/foo.png', path.resolve('./dist/index.html'), path.resolve('./dist'))).to.eql(path.resolve('dist/dist/images/foo.png'));
expect(utils.getSourcepath('/images/foo.png', path.resolve('./dist/index.html'), path.resolve('./dist'))).to.eql(path.resolve('dist/images/foo.png'));
```

**Comment by kilianc** [comment]
trying to create a failing test case

**Comment by kilianc** [comment]
```
events.js:141
      throw er; // Unhandled 'error' event
      ^
Error: ENOENT: no such file or directory, open '/Volumes/my/project/dist/dist/images/logo-something@2x.png'
    at Error (native)
```

```js
gulp.task('inline:html', function () {
  return gulp.src('dist/**/*.html')
    .pipe(plugins.inlineSource({
      svgAsImage: true
    }))
    .pipe(gulp.dest('dist'))
})
```

```html
<img src="/dist/images/logo-something@2x.png" width="121" height="17" inline>
```

**Comment by kilianc** [comment]
N.B. the HTML file path is: `/dist/index.html`

**Comment by kilianc** [comment]
I just realized that the bug is probably in the gulp task not the library :dizzy_face:

**Comment by popeindustries** [comment]
I think if you add the following:
```js
.pipe(plugins.inlineSource({
      svgAsImage: true,
      rootpath: process.cwd()
    }))
```
it might work

**Comment by kilianc** [comment]
it totally does and you are my hero, considering the issue is not even related to this repo.

:+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1: :+1:

**Comment by popeindustries** [comment]
No worries. I added more tests, and that's never a bad thing.
