### ISSUE TITLE
publishing a new version?

### ISSUE THREAD

**Issue by tanhauhau** [popeindustries/inline-source#270]
Hi, I've noticed the last version published (7.2.0) has been more than a year ago, and you've consistently upgrade dependencies (such as terser v4 -> v5), i wonder would you be considering publishing a new version to npm?

**Comment by XhmikosR** [comment]
@popeindustries could you take care of this please? There are more dep PRs and svgo needs some code changes but after that you should be able to cut a new version :)

**Comment by XhmikosR** [comment]
@popeindustries could you also cut a new inline-source-cli release please?

Thanks!
