### ISSUE TITLE
Add possibility to inline remote files

### ISSUE THREAD

**Issue by dsebastien** [popeindustries/inline-source#28]
It would be nice to be able to do something like:

```
<!-- inline https://storage.googleapis.com/code.getmdl.io/1.0.6/material.min.js -->
<script inline src="https://storage.googleapis.com/code.getmdl.io/1.0.6/material.min.js"></script>
```

**Comment by popeindustries** [comment]
[sorry for the delay - seems my earlier reply didn't go through]

This is an interesting idea, but my initial feeling is that it would add too much additional complexity for little benefit. Any sort of remote fetching would require a persistent cache (and cache invalidation routine) to prevent unnecessary downloads. It would also complicate the sync api. I'll leave this issue open in case others would like to vote their interest.

**Comment by dsebastien** [comment]
Couldn't caching support be considered a further improvement rather than a must have?
For my use case it would be nice to have but not a requirement per se.

**Comment by popeindustries** [comment]
I would think the most common  scenario would be to build on save (at least it is for me).

**Comment by dsebastien** [comment]
Heh, it indeed depends on what you're trying to achieve. In my case, I only need to inline resources when the production build is created (i.e., not often). During development I try to avoid as many manipulations as I can.

But just consider that the feature isn't there today at all, so having it, albeit without all the bonus caching support would still be a plus for some people :)

**Comment by catdad** [comment]
I have a scenario for this. I am building an html report from some performance tests that is output in Jenkins artifacts. When Jenkins opens html pages, however, it blocks remote scripts, so my page doesn't load. Since I am already building that html page with gulp, it should be super convenient to inline all of the remote scripts... except that all the existing libs don't support remote files.

**Comment by tommedema** [comment]
Agree that this is a good feature.

@popeindustries if you don't want to implement the fetching, perhaps you can add a `onRemoteResource` callback in which the user implements the fetching manually and returns a file as binary.

**Comment by popeindustries** [comment]
I've begun rewriting the codebase to use `async/await` and promises. In practice, this means the `sync` api will disappear, and there should be no technical hurdle to implementing this. I therefore plan to include a basic version of this feature in the same `v6` release.
