### ISSUE TITLE
Absolute URLs in CSS - More info needed

### ISSUE THREAD

**Issue by alexnewmannn** [popeindustries/inline-source#30]
Hey!
https://github.com/fmal/gulp-inline-source/issues/22 I saw this issue on a gulp plugin and it's something that is going to affect me very soon. I have tried to play around with the current config in the node_module and can't seem to see this built in. 

I am happy to attempt to try and implement this solution if there's not already a way of doing this?
Essentially

Given I am in `Theme/dist/css/styles.css` and the code is
```css
background: url('../images/icons.svg'); // Translates to Theme/dist/images/icons.svg
```
I should expect to see 
```html
<style>
   background: url('images/icons.svg'); // Translates to Theme/dist/images/icons.svg
</style>
```

Given I am in `Theme/dist/css/main/styles.css` and the code is
```css
background: url('../../images/icons.svg'); // Translates to Theme/dist/images/icons.svg
```
I should expect to see 
```html
<style>
   background: url('images/icons.svg'); // Translates to Theme/dist/images/icons.svg
</style>
```

I think the way to do this, if it isn't already implemented (fairly sure its not), would be to take the current `source.parentContext.htmlPath` and work out the difference between that and the `source.filePath` possibly using `path.relative`?

I'll have a play around with this if this is something you guys are interested in and is something that isn't already implemented.

**Comment by popeindustries** [comment]
Ho!
This kind of transform isn't implemented, and to be honest, it feels a little out of scope. I don't do any source transforms apart from minification, and anything else could be handled before passing content to *inline-source*. There is a real risk of turning this project into a mini-build system, so I think it's important to hold the line when there are other alternatives. 

If you absolutely must have this, it would be trivial to write your own css [handler](https://github.com/popeindustries/inline-source#custom-handlers) to enable this behaviour. Alternatively, I may be open to adding generic hooks of the type `before`, `beforeEach`, `afterEach`, `after` to enable more fine grained source manipulation at various points during the pipeline.
