### ISSUE TITLE
Add support for other script types (feature request)

### ISSUE THREAD

**Issue by progers** [popeindustries/inline-source#34]
inline-source will ignore scripts with unrecognized types such as type="text/x-my-template". It would be convenient to add an option for processing other script types.

Various templating libraries use custom types such as text/x-handlebars-template.

**Comment by progers** [comment]
For anyone else who finds this, it's not too difficult to do with custom handlers:
var accepMyTemplateType = function(source, context, next) {
    if (source.fileContent && !source.content && (source.type === 'text/x-my-template')) {
        source.content = source.fileContent;
        next();
    } else {
        next();
    }
}

This feature request is to add a builtin option for an array of additional source types that are accepted.

**Comment by popeindustries** [comment]
The reason for being strict with types is that, if the content is to be compressed, you have to be certain it's a valid format the compressor understands. Can an inlined handlebars template be compressed with uglify? As you point out, custom handlers are an acceptable way to get around this by allowing you to take responsibility for any necessary processing, compression included.

What kind of api are you looking for?

```js
inline(htmlpath, {
  types: {
    js: ['text/x-my-template']
  }
}, function (err, html) {
  // Do something with html
});
```

**Comment by progers** [comment]
After a full nights sleep I agree with you that the custom handlers mechanism is the best way to solve this. Thanks for taking the time to respond. Lets close this.
