### ISSUE TITLE
Support inlining HTML imports

### ISSUE THREAD

**Issue by seaneking** [popeindustries/inline-source#35]
Would be great to have support for inlining HTML imports (eg: `<link rel="import" href="./my-component.html" inline />`). I know you could do a custom handler, but seeing as Web Components and Polymer are gaining popularity would be awesome to have out-of-the-box. Can use [html-minifier](https://github.com/kangax/html-minifier) as the optional minifier.

**Comment by popeindustries** [comment]
Do you have a link to a spec or other documentation? This might be a little difficult without some sort of `type` attribute, since it looks an awful lot like a css inline.

**Comment by seaneking** [comment]
Sure thing, https://www.w3.org/TR/html-imports/#link-type-import (has type of `text/html`). Not ratified yet, but native in Chrome and polyfilled elsewhere with webcomponents.js.

**Comment by popeindustries** [comment]
It seems like html imports as a standard are dead. Closing for now.
