### ISSUE TITLE
escape closing <script> in js file content does not work

### ISSUE THREAD

**Issue by twittmann** [popeindustries/inline-source#36]
The script escapment is somehow repaired: 
when I interpreted it right urglify repairs the escaped characters so closing script tag is unquoted afterward again.

But even when I put it afterwards it was repaired again- I'm sorry I did not do further investigations on that. 
I used another trick - and splitted the string with '+'  which worked for me.
When I'm right the closing script tag has to be always in quote so this should be legal.
in file js.js : 
```
if (RE_SCRIPT.test(source.content)) {
   source.content = source.content.replace(RE_SCRIPT, '\x3C/scri\'+\'pt>');
}
```
Thanx Tobias

**Comment by popeindustries** [comment]
Unfortunately, I don't think that will work because you're making an assumption about the kind of outer quotes being used (`'` or `"`). In any case, when I run the test with compression on, Uglify doesn't substitute `<` for `\x3c`.
