### ISSUE TITLE
Specific html code causes failures

### ISSUE THREAD

**Issue by wjwzwy** [popeindustries/inline-source#38]
`<span style="display: inline-block;" ng-if="x>0"></span>`

The above html code causes failures of inline-source` when I am running gulp-inline-source. My guess is  that the parser doesn't correctly avoid the code that contains both "inline" and ">". 

You may want to take a look at this issue.

**Comment by popeindustries** [comment]
Thanks for catching that. Should be fixed in 4.2.6
