### ISSUE TITLE
Inline SVG without optional x, y or viewBox attribute

### ISSUE THREAD

**Issue by stonio** [popeindustries/inline-source#41]
Let's consider a SVG image without `x`, `y` or `viewBox` attributes defined in `svg` element.

If we inline this image included in a HTML document, these 3 parameters are forcibly inserted in output.
Can we omit these optional attributes if not set?

Example
=====

Content of foo.svg
```xml
<?xml version="1.0" encoding="utf-8"?><svg version="1.1" id="Layer_1" xmlns="http://www.w3.org/2000/svg" xmlns:xlink="http://www.w3.org/1999/xlink" xml:space="preserve"><circle r="999"/></svg>
```

Actual result
```xml
<svg x="0" y="0" viewBox="0 0 100 100" id="Layer_1" xml:space="preserve"><circle r="999"/></svg>
```

Expected result
```xml
<svg id="Layer_1" xml:space="preserve"><circle r="999"/></svg>
```

**Comment by popeindustries** [comment]
Yeah, that was probably unnecessary, but I'm afraid it will have to wait a little bit since it's a breaking change. I can probably fix it as part of the changes related to #31
