### ISSUE TITLE
inline of minified jQuery mobile causes page error

### ISSUE THREAD

**Issue by sticilface** [popeindustries/inline-source#45]
I've managed to get everything to work... except if i inline 

```
jquery.mobile-1.4.5.min.js"
```

I have compression turned off...  I'd just like to use the minified versions of the CDNs...  
It is important that the whole site is bundled as 1 file.  its for an ESP8266 that doesn't handle simultaneous requests well. 

I get 
```
SyntaxError: Unexpected EOF
(anonymous function)index.htm:27
```

if i inline the unminified  `jquery.mobile-1.4.5.js`  then it works fine.  If I inline the unminified but compress it then i get the same error...  unexpected EOF.. 

any ideas?

**Comment by popeindustries** [comment]
That is a strange one. I'm guessing you only get this error on the device, or in other browsers too? And `27` must be the line number? No column number available? If you open the html file with minified content in a text editor with syntax highlighting, does it look funny, or is it parsed correctly? Minification must be introducing some "illegal" characters when placed in the `<head>`.

**Comment by popeindustries** [comment]
I think I've found (and hopefully fixed) the problem. It probably has to do with a `</script>` in the inlined content. I've released the fix as v5.0.2. Let me know if it turns out to be something else.

**Comment by sticilface** [comment]
hi,

sorry i meant to reply and forgot.  
I shall test it out and let you know!

**Comment by sticilface** [comment]
ok this fixes the problem for inlining already minified code... however... if i inline the (non-minified version) and set inline-source to compress, it does not error on magnification but the jQuery does not load in the webpage.. and it errors on load. 

```
TypeError: $("[data-role='header']").toolbar is not a function. (In '$("[data-role='header']").toolbar()', '$("[data-role='header']").toolbar' is undefined)
(anonymous function)index.htm:9:47591
jindex.htm:3:27249
fireWithindex.htm:3:28058
readyindex.htm:3:29902
Jindex.htm:3:30262
```

these are functions in the jQuery mobile thingy!
