### ISSUE TITLE
Support viewBox attribute in <symbol>

### ISSUE THREAD

**Issue by davidkpiano** [popeindustries/inline-source#53]
Using e.g., `<symbol id="foo" viewBox="0 0 50 50">` in SVG files is not detected by the plugin, because of this regex: https://github.com/popeindustries/inline-source/blob/ff9ff811f64f3f0ce1817cb624a126e80ecf3366/lib/imgSVG.js#L13

**Comment by davidkpiano** [comment]
Thank you @popeindustries! Do you know when this will be released?

**Comment by popeindustries** [comment]
Already available: https://github.com/popeindustries/inline-source/releases/tag/5.2.2 😉
