### ISSUE TITLE
Does this inline background images specified in css files?

### ISSUE THREAD

**Issue by tommedema** [popeindustries/inline-source#58]
This is a requirement for my use case (ie inline background images in css files as base64)

**Comment by popeindustries** [comment]
Unfortunately this does not. It inlines content into HTML files in a declarative way (with an `inline` attribute, or similar). I'm not sure how you could declaratively flag background css image inlining, but I'm open for suggestions.

**Comment by cecilpeng** [comment]
why not use query string, such as ?inline

**Comment by dinony** [comment]
Or if `inline` attribute is used on stylesheet all urls in css are inlined too, otherwise not.

**Comment by dinony** [comment]
Or another solution: 

First use [postcss-assets](https://github.com/borodean/postcss-assets#inlining-files) `inline` feature and then inline the css file with this tool.

postcss-assets inline feature works like this:

```css
.test {
  background-image: inline({somePath})
}
```

will gen

```css
.test {
  background-image: url('data:image/...........')
}
```

There you go 👍
