### ISSUE TITLE
Add ability to override compress per script tag

### ISSUE THREAD

**Issue by DannyJF** [popeindustries/inline-source#68]
Generally I want to compress inline script tags, but sometimes I am given vendor code which is already minified. Re-minifying is unnecessary and makes debugging harder. I'd like to be able to override the compress value on the script tag.

I was going to do a pull request, but I'm having trouble on the tests. This is what i have so far. Can anyone take this over or point me in the correct direction on the tests?

```
<script src="/path/to/assets.js" inline compress="false"></script>

...

module.exports = function js(source, context, next) {
  // Handle sync
  next = next || noop;

  if (source.fileContent && !source.content && source.type == 'js') {
    try {
      var compress;
      if (typeof source.attributes.compress !== 'undefined') {
        compress = (source.attributes.compress == 'true');
      } else {
        compress = source.compress
      }
      source.content = compress
        ? require('uglify-js').minify(source.fileContent, { fromString: true }).code
        : source.fileContent;

      // Escape closing </script>
      if (RE_SCRIPT.test(source.content)) {
        source.content = source.content.replace(RE_SCRIPT, '\\x3C$2');
      }

      next();
    } catch (err) {
      return next(err);
    }
  } else {
    next();
  }
};
```

**Comment by popeindustries** [comment]
There has always been support for defining custom attributes (`<script inline inline-foo="foo" src="foo.js"></script>`), including for overriding the `compress` flag (`<script inline inline-compress=true src="foo.js"></script>`), **however**, there was a bug where `false` wasn't parsed correctly as boolean `false`, so thanks for reporting!

Fixed and released as `6.1.3`
