### ISSUE TITLE
compress option needs space before !important CSS declaration

### ISSUE THREAD

**Issue by easytheretiger** [popeindustries/inline-source#71]
I use Gulp to help automate my email workflow and inline CSS to my HTML file. When I noticed Outlook not rendering the correct link color, I troubleshot and narrowed the issue down to **inline-source does not leave the space character before the !important CSS declaration.**

For example, the inline-souce output ...
`a{color:green!important}`

Will not work, instead it needs to output as ...
`a{color:green !important}`

I've made modifications to my gulpfile.js script to address this issue, but I think it would be ideal if the space was left intact by default to help others. Thanks!

**Comment by popeindustries** [comment]
Hi. This is an issue with the minifier [csso](https://github.com/css/csso) used to compress css files. Most browsers don't care if there is a space or not. Perhaps Outlook is more fussy about whitespace? You should open an issue with them (here is an earlier one: https://github.com/css/csso/issues/366). 

If the file isn't terribly large, you could also disable compression for that source: `<link inline inline-compress=false .../>`.
