### ISSUE TITLE
Support for directories or wildcards as source files

### ISSUE THREAD

**Issue by jameswragg** [popeindustries/inline-source#73]
I'm looking to inline some CSS into a bunch of templates. Does `inline-source` support wildcards, or directories as a source?

If not directly, any suggestions to approach doing this?

**Comment by jameswragg** [comment]
To clarify I'm using `inline-source-cli` in my build task. I guess I could drop that and write a script to use the API.

**Comment by popeindustries** [comment]
For the moment, `inline-source-cli` is a separately maintained project, but I’ve talked with the owner and will probably take it over. Unfortunately, though, it’s summer vacation and I won’t be able to look at it for a couple weeks. I guess your best bet is a script until then. Sorry.
