### ISSUE TITLE
<script> inside JS code

### ISSUE THREAD

**Issue by sochka** [popeindustries/inline-source#9]
Hi, if I have something like the following

index.html
```
<script inline src="main.js">
```
main.js
```
/* lots of code */
var a = "<script></script>";
/*lots of code */
```
</script> tag doesn't get escaped to something like `'</scr'+'ipt>'`. It breaks everything that follows after it.

Originally issued here https://github.com/fmal/gulp-inline-source/issues/9 but I realized the problem is in this repo

**Comment by amccloud** [comment]
Looks like inline-source also unescapes script tags that are already obfuscated.

For example in firebase.js you'll find:
```javascript
a='<script>document.domain="'+document.domain+'";\x3c/script>');
```

Which gets inlined as:
```javascript
a='<script>document.domain="'+document.domain+'";</script>');
```

**Comment by popeindustries** [comment]
@amccloud I've tested this, and in the firebase.js case, it is uglify.js that is converting it back to `</script>`. Since the source is already minified, you should probably run with `{compress: false}`. 

If you have any better suggestions, I'd be happy to try them.
